/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateFilmography201,
  DeleteFilmography200,
  GetActorFilmography200,
  GetFilmographyDetail200,
  UpdateFilmography200
} from '.././model';


export const getGetActorFilmographyResponseMock = (overrideResponse: Partial< GetActorFilmography200 > = {}): GetActorFilmography200 => ({success: true, data: {filmography: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), year: faker.number.int({min: undefined, max: undefined}), type: faker.helpers.arrayElement(['영화','드라마','뮤지컬','연극','웹드라마','광고','기타'] as const), title: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roleType: faker.helpers.arrayElement([faker.helpers.arrayElement(['주연','조연','단역','엑스트라','특별출연'] as const), undefined]), thumbnail: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined])}))}, ...overrideResponse})

export const getCreateFilmographyResponseMock = (overrideResponse: Partial< CreateFilmography201 > = {}): CreateFilmography201 => ({success: true, data: {id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getGetFilmographyDetailResponseMock = (overrideResponse: Partial< GetFilmographyDetail200 > = {}): GetFilmographyDetail200 => ({success: true, data: {id: faker.string.uuid(), year: faker.number.int({min: undefined, max: undefined}), type: faker.helpers.arrayElement(['영화','드라마','뮤지컬','연극','웹드라마','광고','기타'] as const), title: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roleType: faker.helpers.arrayElement([faker.helpers.arrayElement(['주연','조연','단역','엑스트라','특별출연'] as const), undefined]), thumbnail: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined])}, ...overrideResponse})

export const getUpdateFilmographyResponseMock = (overrideResponse: Partial< UpdateFilmography200 > = {}): UpdateFilmography200 => ({success: true, data: {id: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getDeleteFilmographyResponseMock = (overrideResponse: Partial< DeleteFilmography200 > = {}): DeleteFilmography200 => ({success: true, message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetActorFilmographyMockHandler = (overrideResponse?: GetActorFilmography200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetActorFilmography200> | GetActorFilmography200), options?: RequestHandlerOptions) => {
  return http.get('*/api/actors/:actorId/filmography', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetActorFilmographyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateFilmographyMockHandler = (overrideResponse?: CreateFilmography201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateFilmography201> | CreateFilmography201), options?: RequestHandlerOptions) => {
  return http.post('*/api/filmography', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateFilmographyResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetFilmographyDetailMockHandler = (overrideResponse?: GetFilmographyDetail200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetFilmographyDetail200> | GetFilmographyDetail200), options?: RequestHandlerOptions) => {
  return http.get('*/api/filmography/:filmographyId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetFilmographyDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateFilmographyMockHandler = (overrideResponse?: UpdateFilmography200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateFilmography200> | UpdateFilmography200), options?: RequestHandlerOptions) => {
  return http.put('*/api/filmography/:filmographyId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateFilmographyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteFilmographyMockHandler = (overrideResponse?: DeleteFilmography200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteFilmography200> | DeleteFilmography200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/filmography/:filmographyId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteFilmographyResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getFilmographyMock = () => [
  getGetActorFilmographyMockHandler(),
  getCreateFilmographyMockHandler(),
  getGetFilmographyDetailMockHandler(),
  getUpdateFilmographyMockHandler(),
  getDeleteFilmographyMockHandler()
]
