/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  FavoriteType
} from '.././model';
import type {
  AddFavorite201,
  DeleteFavorite200,
  GetFavorites200
} from '.././model';


export const getGetFavoritesResponseMock = (overrideResponse: Partial< GetFavorites200 > = {}): GetFavorites200 => ({success: true, data: {favorites: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), type: faker.helpers.arrayElement(Object.values(FavoriteType)), targetId: faker.string.uuid(), actor: faker.helpers.arrayElement([{id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), imageUrl: faker.helpers.arrayElement([faker.internet.url(), undefined]), age: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), filmography: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), tags: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])}, undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})), pagination: {page: faker.number.int({min: 1, max: undefined}), limit: faker.number.int({min: 1, max: 100}), total: faker.number.int({min: undefined, max: undefined}), totalPages: faker.number.int({min: undefined, max: undefined})}}, ...overrideResponse})

export const getAddFavoriteResponseMock = (overrideResponse: Partial< AddFavorite201 > = {}): AddFavorite201 => ({success: true, data: {id: faker.string.uuid(), type: faker.helpers.arrayElement(Object.values(FavoriteType)), targetId: faker.string.uuid()}, ...overrideResponse})

export const getDeleteFavoriteResponseMock = (overrideResponse: Partial< DeleteFavorite200 > = {}): DeleteFavorite200 => ({success: true, message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetFavoritesMockHandler = (overrideResponse?: GetFavorites200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetFavorites200> | GetFavorites200), options?: RequestHandlerOptions) => {
  return http.get('*/api/favorites', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetFavoritesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAddFavoriteMockHandler = (overrideResponse?: AddFavorite201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AddFavorite201> | AddFavorite201), options?: RequestHandlerOptions) => {
  return http.post('*/api/favorites', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddFavoriteResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteFavoriteMockHandler = (overrideResponse?: DeleteFavorite200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteFavorite200> | DeleteFavorite200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/favorites/:favoriteId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteFavoriteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getFavoritesMock = () => [
  getGetFavoritesMockHandler(),
  getAddFavoriteMockHandler(),
  getDeleteFavoriteMockHandler()
]
