/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../lib/fetcher";
import type { BodyType, ErrorType } from "../../lib/fetcher";
import type {
  CharacterCreateRequest,
  CreateCharacter201,
  DeleteCharacter200,
  GetProjectCharacters200,
  UnauthorizedErrorResponse,
  UpdateCharacter200,
} from ".././model";

/**
 * @summary 캐릭터 목록 조회 (프로젝트별)
 */
export const getProjectCharacters = (projectId: string, signal?: AbortSignal) => {
  return customFetch<GetProjectCharacters200>({ url: `/api/projects/${projectId}/characters`, method: "GET", signal });
};

export const getGetProjectCharactersQueryKey = (projectId?: string) => {
  return [`/api/projects/${projectId}/characters`] as const;
};

export const getGetProjectCharactersQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectCharacters>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectCharactersQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectCharacters>>> = ({ signal }) =>
    getProjectCharacters(projectId, signal);

  return { queryKey, queryFn, enabled: !!projectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectCharacters>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectCharactersQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectCharacters>>>;
export type GetProjectCharactersQueryError = ErrorType<UnauthorizedErrorResponse>;

export function useGetProjectCharacters<
  TData = Awaited<ReturnType<typeof getProjectCharacters>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  projectId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCharacters>>,
          TError,
          Awaited<ReturnType<typeof getProjectCharacters>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjectCharacters<
  TData = Awaited<ReturnType<typeof getProjectCharacters>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  projectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCharacters>>,
          TError,
          Awaited<ReturnType<typeof getProjectCharacters>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjectCharacters<
  TData = Awaited<ReturnType<typeof getProjectCharacters>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 캐릭터 목록 조회 (프로젝트별)
 */

export function useGetProjectCharacters<
  TData = Awaited<ReturnType<typeof getProjectCharacters>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectCharacters>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProjectCharactersQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 캐릭터 생성
 */
export const createCharacter = (
  projectId: string,
  characterCreateRequest: BodyType<CharacterCreateRequest>,
  signal?: AbortSignal
) => {
  return customFetch<CreateCharacter201>({
    url: `/api/projects/${projectId}/characters`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: characterCreateRequest,
    signal,
  });
};

export const getCreateCharacterMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCharacter>>,
    TError,
    { projectId: string; data: BodyType<CharacterCreateRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCharacter>>,
  TError,
  { projectId: string; data: BodyType<CharacterCreateRequest> },
  TContext
> => {
  const mutationKey = ["createCharacter"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCharacter>>,
    { projectId: string; data: BodyType<CharacterCreateRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return createCharacter(projectId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof createCharacter>>>;
export type CreateCharacterMutationBody = BodyType<CharacterCreateRequest>;
export type CreateCharacterMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 캐릭터 생성
 */
export const useCreateCharacter = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCharacter>>,
      TError,
      { projectId: string; data: BodyType<CharacterCreateRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createCharacter>>,
  TError,
  { projectId: string; data: BodyType<CharacterCreateRequest> },
  TContext
> => {
  const mutationOptions = getCreateCharacterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 캐릭터 수정
 */
export const updateCharacter = (characterId: string, characterCreateRequest: BodyType<CharacterCreateRequest>) => {
  return customFetch<UpdateCharacter200>({
    url: `/api/characters/${characterId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: characterCreateRequest,
  });
};

export const getUpdateCharacterMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCharacter>>,
    TError,
    { characterId: string; data: BodyType<CharacterCreateRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCharacter>>,
  TError,
  { characterId: string; data: BodyType<CharacterCreateRequest> },
  TContext
> => {
  const mutationKey = ["updateCharacter"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCharacter>>,
    { characterId: string; data: BodyType<CharacterCreateRequest> }
  > = (props) => {
    const { characterId, data } = props ?? {};

    return updateCharacter(characterId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof updateCharacter>>>;
export type UpdateCharacterMutationBody = BodyType<CharacterCreateRequest>;
export type UpdateCharacterMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 캐릭터 수정
 */
export const useUpdateCharacter = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCharacter>>,
      TError,
      { characterId: string; data: BodyType<CharacterCreateRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCharacter>>,
  TError,
  { characterId: string; data: BodyType<CharacterCreateRequest> },
  TContext
> => {
  const mutationOptions = getUpdateCharacterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 캐릭터 삭제
 */
export const deleteCharacter = (characterId: string) => {
  return customFetch<DeleteCharacter200>({ url: `/api/characters/${characterId}`, method: "DELETE" });
};

export const getDeleteCharacterMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError, { characterId: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteCharacter>>, TError, { characterId: string }, TContext> => {
  const mutationKey = ["deleteCharacter"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCharacter>>, { characterId: string }> = (
    props
  ) => {
    const { characterId } = props ?? {};

    return deleteCharacter(characterId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCharacterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCharacter>>>;

export type DeleteCharacterMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 캐릭터 삭제
 */
export const useDeleteCharacter = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCharacter>>,
      TError,
      { characterId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteCharacter>>, TError, { characterId: string }, TContext> => {
  const mutationOptions = getDeleteCharacterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
