/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateCharacter201,
  DeleteCharacter200,
  GetProjectCharacters200,
  UpdateCharacter200
} from '.././model';


export const getGetProjectCharactersResponseMock = (overrideResponse: Partial< GetProjectCharacters200 > = {}): GetProjectCharacters200 => ({success: true, data: {characters: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), gender: faker.string.alpha({length: {min: 10, max: 20}}), ageRange: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roleType: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), specialTags: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), keywords: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])}))}, ...overrideResponse})

export const getCreateCharacterResponseMock = (overrideResponse: Partial< CreateCharacter201 > = {}): CreateCharacter201 => ({success: true, data: {id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getUpdateCharacterResponseMock = (overrideResponse: Partial< UpdateCharacter200 > = {}): UpdateCharacter200 => ({success: true, data: {id: faker.string.alpha({length: {min: 10, max: 20}}), name: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getDeleteCharacterResponseMock = (overrideResponse: Partial< DeleteCharacter200 > = {}): DeleteCharacter200 => ({success: true, message: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})


export const getGetProjectCharactersMockHandler = (overrideResponse?: GetProjectCharacters200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetProjectCharacters200> | GetProjectCharacters200), options?: RequestHandlerOptions) => {
  return http.get('*/api/projects/:projectId/characters', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProjectCharactersResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateCharacterMockHandler = (overrideResponse?: CreateCharacter201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateCharacter201> | CreateCharacter201), options?: RequestHandlerOptions) => {
  return http.post('*/api/projects/:projectId/characters', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCharacterResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateCharacterMockHandler = (overrideResponse?: UpdateCharacter200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateCharacter200> | UpdateCharacter200), options?: RequestHandlerOptions) => {
  return http.put('*/api/characters/:characterId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCharacterResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteCharacterMockHandler = (overrideResponse?: DeleteCharacter200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteCharacter200> | DeleteCharacter200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/characters/:characterId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteCharacterResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getCharactersMock = () => [
  getGetProjectCharactersMockHandler(),
  getCreateCharacterMockHandler(),
  getUpdateCharacterMockHandler(),
  getDeleteCharacterMockHandler()
]
