/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateAgencyProfile201,
  UpdateAgencyProfile200
} from '.././model';


export const getCreateAgencyProfileResponseMock = (overrideResponse: Partial< CreateAgencyProfile201 > = {}): CreateAgencyProfile201 => ({success: true, data: {agencyId: faker.string.uuid(), agencyName: faker.string.alpha({length: {min: 10, max: 20}}), representativeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), foundedYear: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), specialties: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])}, ...overrideResponse})

export const getUpdateAgencyProfileResponseMock = (overrideResponse: Partial< UpdateAgencyProfile200 > = {}): UpdateAgencyProfile200 => ({success: true, data: {agencyId: faker.string.uuid(), agencyName: faker.string.alpha({length: {min: 10, max: 20}}), representativeName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), foundedYear: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), specialties: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])}, ...overrideResponse})


export const getCreateAgencyProfileMockHandler = (overrideResponse?: CreateAgencyProfile201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateAgencyProfile201> | CreateAgencyProfile201), options?: RequestHandlerOptions) => {
  return http.post('*/api/agencies/profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateAgencyProfileResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateAgencyProfileMockHandler = (overrideResponse?: UpdateAgencyProfile200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateAgencyProfile200> | UpdateAgencyProfile200), options?: RequestHandlerOptions) => {
  return http.put('*/api/agencies/profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateAgencyProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAgenciesMock = () => [
  getCreateAgencyProfileMockHandler(),
  getUpdateAgencyProfileMockHandler()
]
