/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  NotificationType
} from '.././model';
import type {
  GetNotifications200,
  MarkAllNotificationsAsRead200,
  MarkNotificationAsRead200
} from '.././model';


export const getGetNotificationsResponseMock = (overrideResponse: Partial< GetNotifications200 > = {}): GetNotifications200 => ({success: true, data: {notifications: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), type: faker.helpers.arrayElement(Object.values(NotificationType)), title: faker.string.alpha({length: {min: 10, max: 20}}), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isRead: faker.datatype.boolean(), relatedId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})), unreadCount: faker.number.int({min: undefined, max: undefined}), pagination: {page: faker.number.int({min: 1, max: undefined}), limit: faker.number.int({min: 1, max: 100}), total: faker.number.int({min: undefined, max: undefined}), totalPages: faker.number.int({min: undefined, max: undefined})}}, ...overrideResponse})

export const getMarkNotificationAsReadResponseMock = (overrideResponse: Partial< MarkNotificationAsRead200 > = {}): MarkNotificationAsRead200 => ({success: true, ...overrideResponse})

export const getMarkAllNotificationsAsReadResponseMock = (overrideResponse: Partial< MarkAllNotificationsAsRead200 > = {}): MarkAllNotificationsAsRead200 => ({success: true, data: {updatedCount: faker.number.int({min: undefined, max: undefined})}, ...overrideResponse})


export const getGetNotificationsMockHandler = (overrideResponse?: GetNotifications200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetNotifications200> | GetNotifications200), options?: RequestHandlerOptions) => {
  return http.get('*/api/notifications', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNotificationsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMarkNotificationAsReadMockHandler = (overrideResponse?: MarkNotificationAsRead200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<MarkNotificationAsRead200> | MarkNotificationAsRead200), options?: RequestHandlerOptions) => {
  return http.put('*/api/notifications/:notificationId/read', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMarkNotificationAsReadResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getMarkAllNotificationsAsReadMockHandler = (overrideResponse?: MarkAllNotificationsAsRead200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<MarkAllNotificationsAsRead200> | MarkAllNotificationsAsRead200), options?: RequestHandlerOptions) => {
  return http.put('*/api/notifications/read-all', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getMarkAllNotificationsAsReadResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getNotificationsMock = () => [
  getGetNotificationsMockHandler(),
  getMarkNotificationAsReadMockHandler(),
  getMarkAllNotificationsAsReadMockHandler()
]
