/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ActorDashboardStats,
  AgencyDashboardStats,
  GetDashboardStats200
} from '.././model';


export const getGetDashboardStatsResponseActorDashboardStatsMock = (overrideResponse: Partial<ActorDashboardStats> = {}): ActorDashboardStats => ({...{profileViews: faker.number.int({min: undefined, max: undefined}), likes: faker.number.int({min: undefined, max: undefined}), contactRequests: faker.number.int({min: undefined, max: undefined}), profileCompleteness: faker.number.int({min: 0, max: 100})}, ...overrideResponse});

export const getGetDashboardStatsResponseAgencyDashboardStatsMock = (overrideResponse: Partial<AgencyDashboardStats> = {}): AgencyDashboardStats => ({...{activeProjects: faker.number.int({min: undefined, max: undefined}), favoriteActors: faker.number.int({min: undefined, max: undefined}), sentContacts: faker.number.int({min: undefined, max: undefined}), totalCharacters: faker.number.int({min: undefined, max: undefined})}, ...overrideResponse});

export const getGetDashboardStatsResponseMock = (overrideResponse: Partial< GetDashboardStats200 > = {}): GetDashboardStats200 => ({success: true, data: faker.helpers.arrayElement([{...getGetDashboardStatsResponseActorDashboardStatsMock()},{...getGetDashboardStatsResponseAgencyDashboardStatsMock()},]), ...overrideResponse})


export const getGetDashboardStatsMockHandler = (overrideResponse?: GetDashboardStats200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetDashboardStats200> | GetDashboardStats200), options?: RequestHandlerOptions) => {
  return http.get('*/api/dashboard/stats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDashboardStatsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getDashboardMock = () => [
  getGetDashboardStatsMockHandler()
]
