/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */

/**
 * 작품 카테고리
 */
export type JobCategory = typeof JobCategory[keyof typeof JobCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobCategory = {
  단편영화: '단편영화',
  장편영화: '장편영화',
  웹드라마: '웹드라마',
  광고: '광고',
  뮤직비디오: '뮤직비디오',
  기타: '기타',
} as const;
