/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateShowreel201,
  DeleteShowreel200,
  GetActorShowreels200,
  UpdateShowreel200
} from '.././model';


export const getGetActorShowreelsResponseMock = (overrideResponse: Partial< GetActorShowreels200 > = {}): GetActorShowreels200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{showreels: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), title: faker.string.alpha({length: {min: 10, max: 20}}), duration: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), thumbnail: faker.helpers.arrayElement([faker.internet.url(), undefined]), videoUrl: faker.helpers.arrayElement([faker.internet.url(), undefined]), roleType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), workTitle: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), year: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), genre: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), role: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), representativeGenre: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tags: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])})), undefined])}, undefined]), ...overrideResponse})

export const getCreateShowreelResponseMock = (overrideResponse: Partial< CreateShowreel201 > = {}): CreateShowreel201 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), videoUrls: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.internet.url())), undefined])}, undefined]), ...overrideResponse})

export const getUpdateShowreelResponseMock = (overrideResponse: Partial< UpdateShowreel200 > = {}): UpdateShowreel200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), ...overrideResponse})

export const getDeleteShowreelResponseMock = (overrideResponse: Partial< DeleteShowreel200 > = {}): DeleteShowreel200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getGetActorShowreelsMockHandler = (overrideResponse?: GetActorShowreels200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetActorShowreels200> | GetActorShowreels200), options?: RequestHandlerOptions) => {
  return http.get('*/api/actors/:actorId/showreels', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetActorShowreelsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateShowreelMockHandler = (overrideResponse?: CreateShowreel201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateShowreel201> | CreateShowreel201), options?: RequestHandlerOptions) => {
  return http.post('*/api/showreels', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateShowreelResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateShowreelMockHandler = (overrideResponse?: UpdateShowreel200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateShowreel200> | UpdateShowreel200), options?: RequestHandlerOptions) => {
  return http.put('*/api/showreels/:showreelId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateShowreelResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteShowreelMockHandler = (overrideResponse?: DeleteShowreel200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteShowreel200> | DeleteShowreel200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/showreels/:showreelId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteShowreelResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getShowreelsMock = () => [
  getGetActorShowreelsMockHandler(),
  getCreateShowreelMockHandler(),
  getUpdateShowreelMockHandler(),
  getDeleteShowreelMockHandler()
]
