/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../lib/fetcher";
import type { BodyType, ErrorType } from "../../lib/fetcher";
import type {
  CreateShowreel201,
  CreateShowreelBody,
  DeleteShowreel200,
  GetActorShowreels200,
  ShowreelCreateRequest,
  UnauthorizedErrorResponse,
  UpdateShowreel200,
} from ".././model";

/**
 * @summary 쇼릴 목록 조회
 */
export const getActorShowreels = (actorId: string, signal?: AbortSignal) => {
  return customFetch<GetActorShowreels200>({ url: `/api/actors/${actorId}/showreels`, method: "GET", signal });
};

export const getGetActorShowreelsQueryKey = (actorId?: string) => {
  return [`/api/actors/${actorId}/showreels`] as const;
};

export const getGetActorShowreelsQueryOptions = <
  TData = Awaited<ReturnType<typeof getActorShowreels>>,
  TError = ErrorType<unknown>,
>(
  actorId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActorShowreelsQueryKey(actorId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getActorShowreels>>> = ({ signal }) =>
    getActorShowreels(actorId, signal);

  return { queryKey, queryFn, enabled: !!actorId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getActorShowreels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetActorShowreelsQueryResult = NonNullable<Awaited<ReturnType<typeof getActorShowreels>>>;
export type GetActorShowreelsQueryError = ErrorType<unknown>;

export function useGetActorShowreels<
  TData = Awaited<ReturnType<typeof getActorShowreels>>,
  TError = ErrorType<unknown>,
>(
  actorId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorShowreels>>,
          TError,
          Awaited<ReturnType<typeof getActorShowreels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetActorShowreels<
  TData = Awaited<ReturnType<typeof getActorShowreels>>,
  TError = ErrorType<unknown>,
>(
  actorId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActorShowreels>>,
          TError,
          Awaited<ReturnType<typeof getActorShowreels>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetActorShowreels<
  TData = Awaited<ReturnType<typeof getActorShowreels>>,
  TError = ErrorType<unknown>,
>(
  actorId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 쇼릴 목록 조회
 */

export function useGetActorShowreels<
  TData = Awaited<ReturnType<typeof getActorShowreels>>,
  TError = ErrorType<unknown>,
>(
  actorId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getActorShowreels>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetActorShowreelsQueryOptions(actorId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 쇼릴 생성
 */
export const createShowreel = (createShowreelBody: BodyType<CreateShowreelBody>, signal?: AbortSignal) => {
  const formData = new FormData();
  if (createShowreelBody.videos !== undefined) {
    createShowreelBody.videos.forEach((value) => formData.append(`videos`, value));
  }
  formData.append(`roleType`, createShowreelBody.roleType);
  formData.append(`workTitle`, createShowreelBody.workTitle);
  if (createShowreelBody.year !== undefined) {
    formData.append(`year`, createShowreelBody.year.toString());
  }
  if (createShowreelBody.genre !== undefined) {
    formData.append(`genre`, createShowreelBody.genre);
  }
  if (createShowreelBody.role !== undefined) {
    formData.append(`role`, createShowreelBody.role);
  }
  if (createShowreelBody.representativeGenre !== undefined) {
    formData.append(`representativeGenre`, createShowreelBody.representativeGenre);
  }
  if (createShowreelBody.tags !== undefined) {
    createShowreelBody.tags.forEach((value) => formData.append(`tags`, value));
  }

  return customFetch<CreateShowreel201>({
    url: `/api/showreels`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getCreateShowreelMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createShowreel>>,
    TError,
    { data: BodyType<CreateShowreelBody> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createShowreel>>,
  TError,
  { data: BodyType<CreateShowreelBody> },
  TContext
> => {
  const mutationKey = ["createShowreel"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createShowreel>>,
    { data: BodyType<CreateShowreelBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createShowreel(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof createShowreel>>>;
export type CreateShowreelMutationBody = BodyType<CreateShowreelBody>;
export type CreateShowreelMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 쇼릴 생성
 */
export const useCreateShowreel = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createShowreel>>,
      TError,
      { data: BodyType<CreateShowreelBody> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createShowreel>>,
  TError,
  { data: BodyType<CreateShowreelBody> },
  TContext
> => {
  const mutationOptions = getCreateShowreelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 쇼릴 수정
 */
export const updateShowreel = (showreelId: string, showreelCreateRequest: BodyType<ShowreelCreateRequest>) => {
  return customFetch<UpdateShowreel200>({
    url: `/api/showreels/${showreelId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: showreelCreateRequest,
  });
};

export const getUpdateShowreelMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateShowreel>>,
    TError,
    { showreelId: string; data: BodyType<ShowreelCreateRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateShowreel>>,
  TError,
  { showreelId: string; data: BodyType<ShowreelCreateRequest> },
  TContext
> => {
  const mutationKey = ["updateShowreel"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateShowreel>>,
    { showreelId: string; data: BodyType<ShowreelCreateRequest> }
  > = (props) => {
    const { showreelId, data } = props ?? {};

    return updateShowreel(showreelId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof updateShowreel>>>;
export type UpdateShowreelMutationBody = BodyType<ShowreelCreateRequest>;
export type UpdateShowreelMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 쇼릴 수정
 */
export const useUpdateShowreel = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateShowreel>>,
      TError,
      { showreelId: string; data: BodyType<ShowreelCreateRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateShowreel>>,
  TError,
  { showreelId: string; data: BodyType<ShowreelCreateRequest> },
  TContext
> => {
  const mutationOptions = getUpdateShowreelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 쇼릴 삭제
 */
export const deleteShowreel = (showreelId: string) => {
  return customFetch<DeleteShowreel200>({ url: `/api/showreels/${showreelId}`, method: "DELETE" });
};

export const getDeleteShowreelMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError, { showreelId: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError, { showreelId: string }, TContext> => {
  const mutationKey = ["deleteShowreel"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteShowreel>>, { showreelId: string }> = (props) => {
    const { showreelId } = props ?? {};

    return deleteShowreel(showreelId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteShowreelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteShowreel>>>;

export type DeleteShowreelMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 쇼릴 삭제
 */
export const useDeleteShowreel = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteShowreel>>, TError, { showreelId: string }, TContext>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteShowreel>>, TError, { showreelId: string }, TContext> => {
  const mutationOptions = getDeleteShowreelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
