/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  NoticeType
} from '.././model';
import type {
  GetNoticeDetail200,
  GetNotices200
} from '.././model';


export const getGetNoticesResponseMock = (overrideResponse: Partial< GetNotices200 > = {}): GetNotices200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{notices: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), type: faker.helpers.arrayElement(Object.values(NoticeType)), title: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})), undefined]), pagination: faker.helpers.arrayElement([{page: faker.number.int({min: 1, max: undefined}), limit: faker.number.int({min: 1, max: 100}), total: faker.number.int({min: undefined, max: undefined}), totalPages: faker.number.int({min: undefined, max: undefined})}, undefined])}, undefined]), ...overrideResponse})

export const getGetNoticeDetailResponseMock = (overrideResponse: Partial< GetNoticeDetail200 > = {}): GetNoticeDetail200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.string.uuid(), type: faker.helpers.arrayElement(Object.values(NoticeType)), title: faker.string.alpha({length: {min: 10, max: 20}}), content: faker.string.alpha({length: {min: 10, max: 20}}), views: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, undefined]), ...overrideResponse})


export const getGetNoticesMockHandler = (overrideResponse?: GetNotices200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetNotices200> | GetNotices200), options?: RequestHandlerOptions) => {
  return http.get('*/api/notices', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNoticesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetNoticeDetailMockHandler = (overrideResponse?: GetNoticeDetail200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetNoticeDetail200> | GetNoticeDetail200), options?: RequestHandlerOptions) => {
  return http.get('*/api/notices/:noticeId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNoticeDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getNoticesMock = () => [
  getGetNoticesMockHandler(),
  getGetNoticeDetailMockHandler()
]
