/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  UserType
} from '.././model';
import type {
  GetMyProfile200,
  GetNotificationSettings200,
  UpdateMyProfile200,
  UpdateNotificationSettings200
} from '.././model';


export const getGetMyProfileResponseMock = (overrideResponse: Partial< GetMyProfile200 > = {}): GetMyProfile200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.string.uuid(), email: faker.internet.email(), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(UserType)), profileImage: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]), position: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), agency: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), phone: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), bio: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), fee: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), height: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), weight: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), settings: faker.helpers.arrayElement([{castingNotification: faker.datatype.boolean(), messageNotification: faker.datatype.boolean(), marketingNotification: faker.datatype.boolean()}, undefined])}, undefined]), ...overrideResponse})

export const getUpdateMyProfileResponseMock = (overrideResponse: Partial< UpdateMyProfile200 > = {}): UpdateMyProfile200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), profileImageUrl: faker.helpers.arrayElement([faker.internet.url(), undefined])}, undefined]), ...overrideResponse})

export const getGetNotificationSettingsResponseMock = (overrideResponse: Partial< GetNotificationSettings200 > = {}): GetNotificationSettings200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{castingNotification: faker.datatype.boolean(), messageNotification: faker.datatype.boolean(), marketingNotification: faker.datatype.boolean()}, undefined]), ...overrideResponse})

export const getUpdateNotificationSettingsResponseMock = (overrideResponse: Partial< UpdateNotificationSettings200 > = {}): UpdateNotificationSettings200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{castingNotification: faker.datatype.boolean(), messageNotification: faker.datatype.boolean(), marketingNotification: faker.datatype.boolean()}, undefined]), ...overrideResponse})


export const getGetMyProfileMockHandler = (overrideResponse?: GetMyProfile200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetMyProfile200> | GetMyProfile200), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateMyProfileMockHandler = (overrideResponse?: UpdateMyProfile200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateMyProfile200> | UpdateMyProfile200), options?: RequestHandlerOptions) => {
  return http.put('*/api/users/profile', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateMyProfileResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetNotificationSettingsMockHandler = (overrideResponse?: GetNotificationSettings200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetNotificationSettings200> | GetNotificationSettings200), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/settings/notifications', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNotificationSettingsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateNotificationSettingsMockHandler = (overrideResponse?: UpdateNotificationSettings200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateNotificationSettings200> | UpdateNotificationSettings200), options?: RequestHandlerOptions) => {
  return http.put('*/api/users/settings/notifications', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateNotificationSettingsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUsersMock = () => [
  getGetMyProfileMockHandler(),
  getUpdateMyProfileMockHandler(),
  getGetNotificationSettingsMockHandler(),
  getUpdateNotificationSettingsMockHandler()
]
