/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UploadImage200,
  UploadVideo200
} from '.././model';


export const getUploadImageResponseMock = (overrideResponse: Partial< UploadImage200 > = {}): UploadImage200 => ({success: true, data: {url: faker.internet.url(), filename: faker.string.alpha({length: {min: 10, max: 20}}), size: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), mimeType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})

export const getUploadVideoResponseMock = (overrideResponse: Partial< UploadVideo200 > = {}): UploadVideo200 => ({success: true, data: {url: faker.internet.url(), thumbnailUrl: faker.helpers.arrayElement([faker.internet.url(), undefined]), filename: faker.string.alpha({length: {min: 10, max: 20}}), size: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), duration: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), mimeType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, ...overrideResponse})


export const getUploadImageMockHandler = (overrideResponse?: UploadImage200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UploadImage200> | UploadImage200), options?: RequestHandlerOptions) => {
  return http.post('*/api/upload/image', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadImageResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUploadVideoMockHandler = (overrideResponse?: UploadVideo200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UploadVideo200> | UploadVideo200), options?: RequestHandlerOptions) => {
  return http.post('*/api/upload/video', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUploadVideoResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUploadMock = () => [
  getUploadImageMockHandler(),
  getUploadVideoMockHandler()
]
