/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  JobCategory,
  JobStatus
} from '.././model';
import type {
  CreateJob201,
  DeleteJob200,
  GetJobDetail200,
  GetJobs200,
  UpdateJob200
} from '.././model';


export const getGetJobsResponseMock = (overrideResponse: Partial< GetJobs200 > = {}): GetJobs200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{jobs: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), category: faker.helpers.arrayElement(Object.values(JobCategory)), isPumasi: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), price: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), gender: faker.helpers.arrayElement([faker.helpers.arrayElement(['남자','여자','성별무관'] as const), undefined]), production: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), workTitle: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(JobStatus)), views: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})), undefined]), pagination: faker.helpers.arrayElement([{page: faker.number.int({min: 1, max: undefined}), limit: faker.number.int({min: 1, max: 100}), total: faker.number.int({min: undefined, max: undefined}), totalPages: faker.number.int({min: undefined, max: undefined})}, undefined])}, undefined]), ...overrideResponse})

export const getCreateJobResponseMock = (overrideResponse: Partial< CreateJob201 > = {}): CreateJob201 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), ...overrideResponse})

export const getGetJobDetailResponseMock = (overrideResponse: Partial< GetJobDetail200 > = {}): GetJobDetail200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.string.uuid(), category: faker.helpers.arrayElement(Object.values(JobCategory)), isPumasi: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), price: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), gender: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ageRange: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), production: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), workTitle: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), shootingDate: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), shootingLocation: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), status: faker.helpers.arrayElement(Object.values(JobStatus)), views: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), contactEmail: faker.helpers.arrayElement([faker.internet.email(), undefined]), contactPhone: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, undefined]), ...overrideResponse})

export const getUpdateJobResponseMock = (overrideResponse: Partial< UpdateJob200 > = {}): UpdateJob200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), ...overrideResponse})

export const getDeleteJobResponseMock = (overrideResponse: Partial< DeleteJob200 > = {}): DeleteJob200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getGetJobsMockHandler = (overrideResponse?: GetJobs200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetJobs200> | GetJobs200), options?: RequestHandlerOptions) => {
  return http.get('*/api/jobs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetJobsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateJobMockHandler = (overrideResponse?: CreateJob201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateJob201> | CreateJob201), options?: RequestHandlerOptions) => {
  return http.post('*/api/jobs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateJobResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetJobDetailMockHandler = (overrideResponse?: GetJobDetail200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetJobDetail200> | GetJobDetail200), options?: RequestHandlerOptions) => {
  return http.get('*/api/jobs/:jobId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetJobDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateJobMockHandler = (overrideResponse?: UpdateJob200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateJob200> | UpdateJob200), options?: RequestHandlerOptions) => {
  return http.put('*/api/jobs/:jobId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateJobResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteJobMockHandler = (overrideResponse?: DeleteJob200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteJob200> | DeleteJob200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/jobs/:jobId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteJobResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getJobsMock = () => [
  getGetJobsMockHandler(),
  getCreateJobMockHandler(),
  getGetJobDetailMockHandler(),
  getUpdateJobMockHandler(),
  getDeleteJobMockHandler()
]
