/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  UserType
} from '.././model';
import type {
  DeleteAccount200,
  ForgotPassword200,
  Login200,
  Logout200,
  RefreshToken200,
  ResetPassword200,
  Signup201
} from '.././model';


export const getLoginResponseMock = (overrideResponse: Partial< Login200 > = {}): Login200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{accessToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), user: faker.helpers.arrayElement([{id: faker.string.uuid(), email: faker.internet.email(), name: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(Object.values(UserType)), profileImage: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, undefined])}, undefined]), ...overrideResponse})

export const getSignupResponseMock = (overrideResponse: Partial< Signup201 > = {}): Signup201 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{userId: faker.helpers.arrayElement([faker.string.uuid(), undefined]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), type: faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(UserType)), undefined])}, undefined]), ...overrideResponse})

export const getForgotPasswordResponseMock = (overrideResponse: Partial< ForgotPassword200 > = {}): ForgotPassword200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getResetPasswordResponseMock = (overrideResponse: Partial< ResetPassword200 > = {}): ResetPassword200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getLogoutResponseMock = (overrideResponse: Partial< Logout200 > = {}): Logout200 => ({success: faker.helpers.arrayElement([true, undefined]), ...overrideResponse})

export const getDeleteAccountResponseMock = (overrideResponse: Partial< DeleteAccount200 > = {}): DeleteAccount200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getRefreshTokenResponseMock = (overrideResponse: Partial< RefreshToken200 > = {}): RefreshToken200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}})}, undefined]), ...overrideResponse})


export const getLoginMockHandler = (overrideResponse?: Login200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Login200> | Login200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSignupMockHandler = (overrideResponse?: Signup201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Signup201> | Signup201), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/signup', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSignupResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getForgotPasswordMockHandler = (overrideResponse?: ForgotPassword200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ForgotPassword200> | ForgotPassword200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/forgot-password', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getForgotPasswordResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getResetPasswordMockHandler = (overrideResponse?: ResetPassword200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ResetPassword200> | ResetPassword200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/reset-password', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getResetPasswordResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getLogoutMockHandler = (overrideResponse?: Logout200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Logout200> | Logout200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/logout', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLogoutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteAccountMockHandler = (overrideResponse?: DeleteAccount200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteAccount200> | DeleteAccount200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/auth/account', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteAccountResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getRefreshTokenMockHandler = (overrideResponse?: RefreshToken200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RefreshToken200> | RefreshToken200), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/refresh', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAuthMock = () => [
  getLoginMockHandler(),
  getSignupMockHandler(),
  getForgotPasswordMockHandler(),
  getResetPasswordMockHandler(),
  getLogoutMockHandler(),
  getDeleteAccountMockHandler(),
  getRefreshTokenMockHandler()
]
