/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customFetch } from "../../lib/fetcher";
import type { BodyType, ErrorType } from "../../lib/fetcher";
import type {
  CreateProject201,
  DeleteProject200,
  GetProjectDetail200,
  GetProjects200,
  GetProjectsParams,
  NotFoundErrorResponse,
  ProjectCreateRequest,
  UnauthorizedErrorResponse,
  UpdateProject200,
} from ".././model";

/**
 * @summary 프로젝트 목록 조회
 */
export const getProjects = (params?: GetProjectsParams, signal?: AbortSignal) => {
  return customFetch<GetProjects200>({ url: `/api/projects`, method: "GET", params, signal });
};

export const getGetProjectsQueryKey = (params?: GetProjectsParams) => {
  return [`/api/projects`, ...(params ? [params] : [])] as const;
};

export const getGetProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  params?: GetProjectsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({ signal }) => getProjects(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getProjects>>>;
export type GetProjectsQueryError = ErrorType<UnauthorizedErrorResponse>;

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  params: undefined | GetProjectsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  params?: GetProjectsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  params?: GetProjectsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 프로젝트 목록 조회
 */

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = ErrorType<UnauthorizedErrorResponse>,
>(
  params?: GetProjectsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProjectsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 프로젝트 생성
 */
export const createProject = (projectCreateRequest: BodyType<ProjectCreateRequest>, signal?: AbortSignal) => {
  return customFetch<CreateProject201>({
    url: `/api/projects`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: projectCreateRequest,
    signal,
  });
};

export const getCreateProjectMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProject>>,
    TError,
    { data: BodyType<ProjectCreateRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: BodyType<ProjectCreateRequest> },
  TContext
> => {
  const mutationKey = ["createProject"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProject>>,
    { data: BodyType<ProjectCreateRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createProject(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>;
export type CreateProjectMutationBody = BodyType<ProjectCreateRequest>;
export type CreateProjectMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 프로젝트 생성
 */
export const useCreateProject = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProject>>,
      TError,
      { data: BodyType<ProjectCreateRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: BodyType<ProjectCreateRequest> },
  TContext
> => {
  const mutationOptions = getCreateProjectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 프로젝트 상세 조회
 */
export const getProjectDetail = (projectId: string, signal?: AbortSignal) => {
  return customFetch<GetProjectDetail200>({ url: `/api/projects/${projectId}`, method: "GET", signal });
};

export const getGetProjectDetailQueryKey = (projectId?: string) => {
  return [`/api/projects/${projectId}`] as const;
};

export const getGetProjectDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectDetail>>,
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectDetailQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectDetail>>> = ({ signal }) =>
    getProjectDetail(projectId, signal);

  return { queryKey, queryFn, enabled: !!projectId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectDetail>>>;
export type GetProjectDetailQueryError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>;

export function useGetProjectDetail<
  TData = Awaited<ReturnType<typeof getProjectDetail>>,
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
>(
  projectId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectDetail>>,
          TError,
          Awaited<ReturnType<typeof getProjectDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjectDetail<
  TData = Awaited<ReturnType<typeof getProjectDetail>>,
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
>(
  projectId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectDetail>>,
          TError,
          Awaited<ReturnType<typeof getProjectDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetProjectDetail<
  TData = Awaited<ReturnType<typeof getProjectDetail>>,
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 프로젝트 상세 조회
 */

export function useGetProjectDetail<
  TData = Awaited<ReturnType<typeof getProjectDetail>>,
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
>(
  projectId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectDetail>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetProjectDetailQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary 프로젝트 수정
 */
export const updateProject = (projectId: string, projectCreateRequest: BodyType<ProjectCreateRequest>) => {
  return customFetch<UpdateProject200>({
    url: `/api/projects/${projectId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: projectCreateRequest,
  });
};

export const getUpdateProjectMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProject>>,
    TError,
    { projectId: string; data: BodyType<ProjectCreateRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProject>>,
  TError,
  { projectId: string; data: BodyType<ProjectCreateRequest> },
  TContext
> => {
  const mutationKey = ["updateProject"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProject>>,
    { projectId: string; data: BodyType<ProjectCreateRequest> }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return updateProject(projectId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>;
export type UpdateProjectMutationBody = BodyType<ProjectCreateRequest>;
export type UpdateProjectMutationError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>;

/**
 * @summary 프로젝트 수정
 */
export const useUpdateProject = <
  TError = ErrorType<UnauthorizedErrorResponse | NotFoundErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProject>>,
      TError,
      { projectId: string; data: BodyType<ProjectCreateRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProject>>,
  TError,
  { projectId: string; data: BodyType<ProjectCreateRequest> },
  TContext
> => {
  const mutationOptions = getUpdateProjectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 프로젝트 삭제
 */
export const deleteProject = (projectId: string) => {
  return customFetch<DeleteProject200>({ url: `/api/projects/${projectId}`, method: "DELETE" });
};

export const getDeleteProjectMutationOptions = <
  TError = ErrorType<UnauthorizedErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError, { projectId: string }, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError, { projectId: string }, TContext> => {
  const mutationKey = ["deleteProject"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, { projectId: string }> = (props) => {
    const { projectId } = props ?? {};

    return deleteProject(projectId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>;

export type DeleteProjectMutationError = ErrorType<UnauthorizedErrorResponse>;

/**
 * @summary 프로젝트 삭제
 */
export const useDeleteProject = <TError = ErrorType<UnauthorizedErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError, { projectId: string }, TContext>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteProject>>, TError, { projectId: string }, TContext> => {
  const mutationOptions = getDeleteProjectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
