/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * K-Culture Web API
 * 배우담(K-Culture Web) 플랫폼 API 명세서

## 개요
- 배우와 에이전시를 연결하는 AI 기반 캐스팅 플랫폼
- 시놉시스 기반 배우 추천, 프로젝트 관리, 포트폴리오 관리 기능 제공

## 인증
- JWT Bearer Token 기반 인증
- Access Token 유효기간: 1시간
- Refresh Token 유효기간: 7일

 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  ProjectStatus
} from '.././model';
import type {
  CreateProject201,
  DeleteProject200,
  GetProjectDetail200,
  GetProjects200,
  UpdateProject200
} from '.././model';


export const getGetProjectsResponseMock = (overrideResponse: Partial< GetProjects200 > = {}): GetProjects200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{projects: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), thumbnail: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]), company: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), title: faker.string.alpha({length: {min: 10, max: 20}}), status: faker.helpers.arrayElement(Object.values(ProjectStatus)), progress: faker.helpers.arrayElement([faker.number.int({min: 0, max: 100}), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])})), undefined]), pagination: faker.helpers.arrayElement([{page: faker.number.int({min: 1, max: undefined}), limit: faker.number.int({min: 1, max: 100}), total: faker.number.int({min: undefined, max: undefined}), totalPages: faker.number.int({min: undefined, max: undefined})}, undefined])}, undefined]), ...overrideResponse})

export const getCreateProjectResponseMock = (overrideResponse: Partial< CreateProject201 > = {}): CreateProject201 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.uuid(), undefined]), projectName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), ...overrideResponse})

export const getGetProjectDetailResponseMock = (overrideResponse: Partial< GetProjectDetail200 > = {}): GetProjectDetail200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.string.uuid(), projectName: faker.string.alpha({length: {min: 10, max: 20}}), company: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), projectType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), genre: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), shootingPeriod: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), roleInfo: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), status: faker.helpers.arrayElement(Object.values(ProjectStatus)), characters: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), gender: faker.helpers.arrayElement(['남성','여성','기타'] as const), ageRange: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), roleType: faker.helpers.arrayElement(['주연','조연','단역','특별출연'] as const)})), undefined]), createdAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined]), updatedAt: faker.helpers.arrayElement([`${faker.date.past().toISOString().split('.')[0]}Z`, undefined])}, undefined]), ...overrideResponse})

export const getUpdateProjectResponseMock = (overrideResponse: Partial< UpdateProject200 > = {}): UpdateProject200 => ({success: faker.helpers.arrayElement([true, undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), projectName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), ...overrideResponse})

export const getDeleteProjectResponseMock = (overrideResponse: Partial< DeleteProject200 > = {}): DeleteProject200 => ({success: faker.helpers.arrayElement([true, undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getGetProjectsMockHandler = (overrideResponse?: GetProjects200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetProjects200> | GetProjects200), options?: RequestHandlerOptions) => {
  return http.get('*/api/projects', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProjectsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateProjectMockHandler = (overrideResponse?: CreateProject201 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateProject201> | CreateProject201), options?: RequestHandlerOptions) => {
  return http.post('*/api/projects', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateProjectResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetProjectDetailMockHandler = (overrideResponse?: GetProjectDetail200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetProjectDetail200> | GetProjectDetail200), options?: RequestHandlerOptions) => {
  return http.get('*/api/projects/:projectId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProjectDetailResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateProjectMockHandler = (overrideResponse?: UpdateProject200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateProject200> | UpdateProject200), options?: RequestHandlerOptions) => {
  return http.put('*/api/projects/:projectId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateProjectResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteProjectMockHandler = (overrideResponse?: DeleteProject200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteProject200> | DeleteProject200), options?: RequestHandlerOptions) => {
  return http.delete('*/api/projects/:projectId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteProjectResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getProjectsMock = () => [
  getGetProjectsMockHandler(),
  getCreateProjectMockHandler(),
  getGetProjectDetailMockHandler(),
  getUpdateProjectMockHandler(),
  getDeleteProjectMockHandler()
]
